### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by kellikmullane** [cruizperez/FastAAI#14]
Hey there! Thanks so much for this tool, it's exactly what I was looking for! 

I was able to install FastAAI easily using pip install, and made sure all the dependencies installed properly. However, I keep getting the same error message anytime I run build_db (this is the only module I've tried thus far). Here's the line of code I'm running:

fastaai build_db --genomes Genomes_85_5/ --threads 20 --verbose --output Halomonas_fAAI_Build --database Halomonas_Build_DB.db --compress

I tried it both on a server that has Python 3.6 installed, and on my own computer that has Python 3.9 installed. Here's the error I get with Python 3.6:

 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 10: invalid start byte

And here's the error I get with Python 3.9 (similar but slightly different):

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 26: invalid continuation byte

Any suggestions on what could be going wrong, or how to resolve this issue?

Thank you!!

**Comment by nicolettacommins** [comment]
I'm having the same error with the following traceback:

Traceback (most recent call last):
  File "/home/nac18/anaconda3/envs/panaroo/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/nac18/anaconda3/envs/panaroo/lib/python3.7/site-packages/fastaai/fastaai.py", line 1377, in run_build
    input_file.preprocess()
  File "/home/nac18/anaconda3/envs/panaroo/lib/python3.7/site-packages/fastaai/fastaai.py", line 1163, in preprocess
    self.genome_to_protein()
  File "/home/nac18/anaconda3/envs/panaroo/lib/python3.7/site-packages/fastaai/fastaai.py", line 963, in genome_to_protein
    mn.run_for_fastaai()
  File "/home/nac18/anaconda3/envs/panaroo/lib/python3.7/site-packages/fastaai/fastaai.py", line 789, in run_for_fastaai
    self.import_sequences()
  File "/home/nac18/anaconda3/envs/panaroo/lib/python3.7/site-packages/fastaai/fastaai.py", line 519, in import_sequences
    s = s.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nac18/anaconda3/envs/panaroo/bin/fastaai", line 8, in <module>
    sys.exit(main())
  File "/home/nac18/anaconda3/envs/panaroo/lib/python3.7/site-packages/fastaai/fastaai.py", line 4509, in main
    build_db(genomes, proteins, hmms, db_name, output, threads, verbose, do_comp)
  File "/home/nac18/anaconda3/envs/panaroo/lib/python3.7/site-packages/fastaai/fastaai.py", line 1546, in build_db
    for result in pool.imap(run_build, imported_files.in_files):
  File "/home/nac18/anaconda3/envs/panaroo/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte

Did you end up having any luck?

**Comment by kellikmullane** [comment]
@nicolettacommins I wasn't able to fix this issue specifically, but I was able to find a workaround that allowed me to use FastAAI. I found that if I generated protein sequences using an external program (I used GeneMarkS-2) and used the resulting .faa files to create a database (build_db) & query that database (query_db), that worked just fine. It was only when I tried to start with nucleotide sequences that this issue persisted. Can't guarantee this workaround will work on your machine, but might be worth a try? Good luck!

**Comment by KGerhardt** [comment]
I apologize for the delays. I've had other projects that I've been working on and I'm just coming back to FastAAI now.

This error is being thrown as a result of a text formatting issue that FastAAI is having in reading your genome sequences. Ultimately FastAAI needs to convert the genome sequences into a bytestring representation and I coded it to read the file in that format. Apparently this is an issue on some systems.

I believe I can fix this by reading the files as plain text and then encoding the sequences afterwards. Slightly less efficient, but I don't think it will be a meaningful change in overall runtime. I will update this thread again after I have fixed this and a few other issues.
