### ISSUE TITLE
Matrix output is broken

### ISSUE THREAD

**Issue by FilipeMatteoli** [cruizperez/FastAAI#16]
fastaai db_query runs smoothly on a formatted database. However, it breaks upon usage of matrix output

`fastaai db_query --query ./FastAAI/database/bac_proteidb --target ./FastAAI/database/bac_proteidb --threads 14 --verbose --output FastAAI_matrix --output_style matrix`

Performing an all vs. all query on ./FastAAI/database/bac_proteidb
Perusing database metadata

Calculating AAI
Completion |##################################################|  100.00% ( 548 of 548 ) at 25/05/2023 14:44:00

Finalizing results.
Completion |#################                                 |   35.71% ( 5 of 14 ) at 25/05/2023 14:44:00
Traceback (most recent call last):
  File "/home/filipe/.local/bin/fastaai", line 8, in <module>
    sys.exit(main())
  File "/home/filipe/.local/lib/python3.10/site-packages/fastaai/fastaai.py", line 4613, in main
    db_query(query, target, verbose, output, threads, do_stdev, style, in_mem, store)
  File "/home/filipe/.local/lib/python3.10/site-packages/fastaai/fastaai.py", line 3399, in db_query
    mdb.run()
  File "/home/filipe/.local/lib/python3.10/site-packages/fastaai/fastaai.py", line 3335, in run
    self.db_on_disk()
  File "/home/filipe/.local/lib/python3.10/site-packages/fastaai/fastaai.py", line 3265, in db_on_disk
    self.write_mat_from_files(result_files, tempdir_path)
  File "/home/filipe/.local/lib/python3.10/site-packages/fastaai/fastaai.py", line 3288, in write_mat_from_files
    fh = open(f, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpgi3knqay/partial_results_group_7.txt'

The matrix file is produced with only a small part of the accessions. Any idea how to fix this?

**Comment by FilipeMatteoli** [comment]
In case anyone wants this, this script converts the raw output to a phylip formatted matrix

```
import os
import re

# Specify the directory path where the text files are located
directory = "/path/to_result_folder/"

# Create a dictionary to store the genome names and AAI values
genome_aai_dict = {}

# List all files in the directory and sort them
files = sorted(os.listdir(directory))

# Iterate through each file
for file_name in files:
    # Check if the file is a text file
    if file_name.endswith(".txt"):
        file_path = os.path.join(directory, file_name)
        genome_name = os.path.splitext(file_name)[0]
        
        # Open the file for reading
        with open(file_path, "r") as file:
            # Read the lines in the file
            lines = file.readlines()
            
            # Extract the AAI value from the last column of each line
            aai_values = [re.sub(r'[><%]', '', line.strip().split("\t")[-1]) for line in lines[1:]]
            
            # Add the genome name and AAI values to the dictionary
            genome_aai_dict[genome_name] = aai_values
                
        print("Processed:", file_name)

# Create a new file to store the joined output
output_file_path = os.path.join(directory, "joined_output.phylip")
with open(output_file_path, "w") as output_file:
    # Write the total number of files as the first line
    output_file.write(str(len(files)) + "\n")
    
    # Iterate through the sorted genome names
    for genome_name in sorted(genome_aai_dict.keys()):
        # Get the corresponding AAI values from the dictionary
        aai_values = genome_aai_dict[genome_name]
        
        # Create a new line for each genome with the AAI values joined together
        joined_line = genome_name + "\t" + "\t".join(aai_values) + "\n"
        output_file.write(joined_line)

print("Joined output file created:", output_file_path)
```

**Comment by gewenlong365** [comment]
I believe we have exactly the same problem,thanks~

**Comment by RiescoR** [comment]
Actually, the problem appears to be related with how the multithreading process allocate the chunks it generates. If you use the default threads  (no multithreading) it works... 
Or you can parse the results of the tsv with another script, which should be way faster
